#!/bin/sh

# source: https://gist.github.com/TheHippo/4823bba5aea614306803d8e062d8318e

# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git goimports pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep -v vendor | grep '.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(goimports -l $gofiles)
if [ ! -z "$unformatted" ]; then
  # Some files are not goimport'd. Print message and fail.
  echo >&2 "Go files must be formatted with goimports. Please run \`make go-fmt\`".
  exit 1
fi

if ! golint -set_exit_status "$gofiles"; then
  echo >&2 "golint failed, aborting"
  exit 1
fi
