language: go

go:
  - "1.13.x"

services:
  - docker

dist: bionic
addons:
  apt:
    update: true
    packages:
    - libzmq3-dev
    - xz-utils
    - sqlite3

env:
   - "GO111MODULE=on"

git:
  depth: 1

script:
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint
  - make ci
