name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install package dependencies
      run: |
        sudo apt update
        sudo apt install -y libzmq3-dev sqlite3 libboost-all-dev

    - name: Download bitcoind v0.18.1 binary
      run: |
        wget https://github.com/0xB10C/bademeister-go/releases/download/0.0.0-bitcoind.0.18.1/bitcoind_v0.18.1_for_GitHubActionsCI.tar.xz
        tar xf bitcoind_v0.18.1_for_GitHubActionsCI.tar.xz
        sudo mv bitcoind /usr/local/bin/bitcoind

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get Go dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Run tests (Makefile)
      run: make test

    - name: Build (Makefile)
      run: make build
